name: bnm-iac-ci

on:
  push:
    branches: [ main, ci/cd ]   # adjust as you like
  pull_request:
    branches: [ main ]
  workflow_dispatch:
    inputs:
      run_apply:
        description: 'Run Terraform Apply (manual opt-in)'
        type: boolean
        default: false
      environment:
        description: 'Environment for apply'
        type: environment
        required: false
        default: production

permissions:
  contents: read
  id-token: write     # for AWS OIDC
  actions: read

concurrency:
  group: bnm-iac-ci-${{ github.ref }}
  cancel-in-progress: true

env:
  TF_WORKING_DIR: demo/terraform
  PLAN_JSON: demo/terraform/policy_inputs/plan.json

jobs:
  fmt_validate:
    name: Terraform fmt & validate
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.6.6

      - name: Terraform fmt/validate (no cloud calls)
        working-directory: ${{ env.TF_WORKING_DIR }}
        run: |
          terraform version
          terraform fmt -check -diff -recursive
          terraform init -input=false
          terraform validate

  plan:
    name: Terraform plan (read-only)
    runs-on: ubuntu-latest
    needs: fmt_validate
    steps:
      - uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.6.6

      - name: Configure AWS (read-only, plan only)
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_ARN_READONLY }}
          aws-region: ${{ secrets.AWS_REGION }}

      # Debug: verify OIDC + branch context
      - name: Who am I?
        run: aws sts get-caller-identity
      - name: Show ref & repo (debug)
        run: |
          echo "ref=${{ github.ref }}"
          echo "repository=${{ github.repository }}"

      - name: Terraform plan → plan.json
        working-directory: ${{ env.TF_WORKING_DIR }}
        run: |
          mkdir -p policy_inputs
          terraform init -input=false
          terraform plan -out=tfplan -var="db_password=$(openssl rand -base64 12)"
          terraform show -json tfplan > policy_inputs/plan.json

      - name: Upload plan.json artifact
        uses: actions/upload-artifact@v4
        with:
          name: tf-plan-json
          path: ${{ env.PLAN_JSON }}

  checkov:
    name: Checkov (HCL & plan-aware)
    runs-on: ubuntu-latest
    needs: plan
    steps:
      - uses: actions/checkout@v4

      - name: Download plan.json
        uses: actions/download-artifact@v4
        with:
          name: tf-plan-json
          path: demo/terraform/policy_inputs

      - name: Install Checkov
        run: |
          pipx install checkov || pip3 install -U checkov

      # Soft-fail HCL so JSON/artifacts are still produced
      - name: Checkov HCL scan → JSON (soft-fail)
        run: checkov -d ${{ env.TF_WORKING_DIR }} -o json --soft-fail > checkov_hcl.json

      # Capture exit code for plan scan but don't fail yet
      - name: Checkov plan scan → JSON (capture exit code)
        id: checkov_plan
        run: |
          set +e
          checkov -f ${{ env.PLAN_JSON }} --framework terraform_plan -o json > checkov_plan.json
          echo "exit_code=$?" >> "$GITHUB_OUTPUT"
          set -e

      # Always upload results so the report job can download them
      - name: Upload Checkov results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: checkov-results
          path: |
            checkov_hcl.json
            checkov_plan.json

      # Now gate on plan violations (exit code != 0)
      - name: Gate on Checkov plan failures
        if: steps.checkov_plan.outputs.exit_code != '0'
        run: |
          echo "Checkov plan scan failed (exit ${{ steps.checkov_plan.outputs.exit_code }})"
          exit 1

  opa:
    name: OPA (policy-as-code gate)
    runs-on: ubuntu-latest
    needs: plan
    steps:
      - uses: actions/checkout@v4

      - name: Download plan.json
        uses: actions/download-artifact@v4
        with:
          name: tf-plan-json
          path: demo/terraform/policy_inputs

      - name: Install OPA
        run: |
          curl -L -o opa https://openpolicyagent.org/downloads/latest/opa_linux_amd64
          chmod +x opa && sudo mv opa /usr/local/bin/opa

      # Run OPA, capture exit code, but upload output regardless
      - name: Run OPA (capture exit code)
        id: opa_eval
        run: |
          set +e
          opa eval --format pretty \
            --fail-defined \
            --input ${{ env.PLAN_JSON }} \
            --data policies 'data.terraform.policy.deny' | tee opa_output.txt
          echo "exit_code=$?" >> "$GITHUB_OUTPUT"
          set -e

      - name: Upload OPA output
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: opa-output
          path: opa_output.txt

      - name: Gate on OPA denies
        if: steps.opa_eval.outputs.exit_code != '0'
        run: |
          echo "OPA reported deny rules (exit ${{ steps.opa_eval.outputs.exit_code }})"
          exit 1

  report:
    name: Generate HTML compliance report
    runs-on: ubuntu-latest
    needs: [checkov, opa]
    if: always()   # produce a report even if gates failed
    steps:
      - uses: actions/checkout@v4

      - name: Download plan.json
        uses: actions/download-artifact@v4
        with:
          name: tf-plan-json
          path: demo/terraform/policy_inputs

      - name: Download Checkov results (best-effort)
        uses: actions/download-artifact@v4
        with:
          name: checkov-results
          path: .
        continue-on-error: true

      - name: Download OPA output (best-effort)
        uses: actions/download-artifact@v4
        with:
          name: opa-output
          path: .
        continue-on-error: true

      - name: Build report.html
        run: |
          mkdir -p compliance/reports
          HCL_PATH="checkov_hcl.json"; PLAN_PATH="checkov_plan.json"; OPA_PATH="opa_output.txt"
          HCL_CONTENT=$([ -f "$HCL_PATH" ] && sed 's/&/\&amp;/g; s/</\&lt;/g' "$HCL_PATH" | head -n 200 || echo "(no checkov_hcl.json)")
          PLAN_CONTENT=$([ -f "$PLAN_PATH" ] && sed 's/&/\&amp;/g; s/</\&lt;/g' "$PLAN_PATH" | head -n 200 || echo "(no checkov_plan.json)")
          OPA_CONTENT=$([ -f "$OPA_PATH" ] && sed 's/&/\&amp;/g; s/</\&lt;/g' "$OPA_PATH" || echo "(no opa_output.txt)")
          {
            echo '<!doctype html><html><head><meta charset="utf-8"><title>BNM IaC Compliance Report</title><style>body{font-family:system-ui,Arial;margin:24px} pre{background:#f6f8fa;padding:12px;border-radius:8px;overflow:auto;white-space:pre-wrap}</style></head><body>';
            echo '<h1>BNM IaC Compliance Report</h1>';
            echo "<p><strong>Generated:</strong> $(date -Is)</p>";
            echo '<h2>Terraform Plan (JSON)</h2><pre>'; sed 's/&/\&amp;/g; s/</\&lt;/g' demo/terraform/policy_inputs/plan.json | head -n 200; echo '</pre>';
            echo '<h2>OPA Policy Evaluation</h2><pre>'"$OPA_CONTENT"'</pre>';
            echo '<h2>Checkov (HCL)</h2><pre>'"$HCL_CONTENT"'</pre>';
            echo '<h2>Checkov (Plan)</h2><pre>'"$PLAN_CONTENT"'</pre>';
            echo '</body></html>';
          } > compliance/reports/compliance_report.html

      - name: Upload compliance report
        uses: actions/upload-artifact@v4
        with:
          name: compliance-report
          path: compliance/reports/compliance_report.html

  apply:
    name: Terraform Apply (manual opt-in)
    runs-on: ubuntu-latest
    if: ${{ github.event_name == 'workflow_dispatch' && inputs.run_apply }}
    needs: [plan, checkov, opa]
    environment: ${{ inputs.environment }}
    steps:
      - uses: actions/checkout@v4

      - name: Configure AWS (writer role)
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_ARN_APPLY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.6.6

      - name: Apply (requires env approval; not run by default)
        working-directory: ${{ env.TF_WORKING_DIR }}
        run: |
          terraform init -input=false
          terraform apply -auto-approve -var="db_password=$(openssl rand -base64 12)"


