name: pre-commit
on:
  pull_request:
  push:
    branches: [ main ]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.7.5

      - name: Setup TFLint
        uses: terraform-linters/setup-tflint@v5
        with:
          tflint_version: latest

      - name: Show versions
        run: |
          terraform -version
          tflint --version
          command -v terraform

      
      - name: Export Terraform path for hooks
        run: echo "PCT_TFPATH=$(command -v terraform)" >> "$GITHUB_ENV"

      - name: Run pre-commit
        uses: pre-commit/action@v3.0.1
        env:
          
          PCT_TFPATH: ${{ env.PCT_TFPATH }}
        with:
          extra_args: --all-files
